/**
 * SLICER ÖNİZLEMESİ ÇIKARICILARI.
 *
 * Kart görseli artık buradan geliyor (Plan D): kendi çizimimiz baskı YOLLARINI çiziyordu ve
 * model beyaz bir siluetten ibaret kalıyordu; slicer gerçek yüzeyi ışıklandırılmış hâlde
 * dosyaya gömüyor. Ölçüldü (16 Ağu 2026): 4 yazıcının 3'ü gcode yorumu, 1'i (Bambu) 3MF zip.
 *
 * Zip ayrıştırması sessizce bozulabilecek türden: yanlış ofset → bozuk PNG → kart görselsiz
 * kalır ama hata düşmez. Bu yüzden gerçek bir zip kurulup uçtan uca doğrulanıyor.
 */
import zlib from "node:zlib";
import { describe, expect, it } from "vitest";
import { gcodeOnizlemesi, zip3mfOnizlemesi, type AralikOkuyucu } from "./slicer-preview";

/** 1×1 saydam PNG (gerçek, geçerli baytlar). */
const PNG_1x1 = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
  "base64"
);

/** Verilen ölçüyü taşıyan sahte ama GEÇERLİ başlıklı PNG (IHDR alanları düzeltilir). */
function pngOlcuyle(genislik: number, yukseklik: number): Buffer {
  const b = Buffer.from(PNG_1x1);
  b.writeUInt32BE(genislik, 16);
  b.writeUInt32BE(yukseklik, 20);
  return b;
}

// ───────────────────────── gcode ─────────────────────────

describe("gcode gömülü önizlemesi", () => {
  function blok(genislik: number, yukseklik: number, png: Buffer): string {
    const b64 = png.toString("base64");
    const satirlar = (b64.match(/.{1,60}/g) ?? []).map((x) => `; ${x}`).join("\n");
    return `; thumbnail begin ${genislik}x${yukseklik} ${png.length}\n${satirlar}\n; thumbnail end\n`;
  }

  it("gömülü PNG'yi çıkarır", () => {
    const png = pngOlcuyle(320, 320);
    const r = gcodeOnizlemesi(`; generated by OrcaSlicer\n${blok(320, 320, png)}G1 X0\n`);
    expect(r).not.toBeNull();
    expect(r!.genislik).toBe(320);
    expect(r!.png.subarray(1, 4).toString()).toBe("PNG");
  });

  it("birden çok blok varsa EN BÜYÜĞÜNÜ seçer", () => {
    // Orca hem 320 hem 800 gömüyor (ölçüldü). Kartta büyük olan gerekli.
    const kucuk = blok(320, 320, pngOlcuyle(320, 320));
    const buyuk = blok(800, 800, pngOlcuyle(800, 800));
    const r = gcodeOnizlemesi(`${kucuk}${buyuk}`);
    expect(r!.genislik).toBe(800);
  });

  it("blok yoksa null — çağıran geri düşüşe geçer", () => {
    expect(gcodeOnizlemesi("; generated by X\nG1 X0 Y0\n")).toBeNull();
  });

  it("bozuk/boş blok hesabı patlatmaz", () => {
    expect(gcodeOnizlemesi("; thumbnail begin 100x100 0\n; thumbnail end\n")).toBeNull();
  });

  it("SALT-CR satır sonlu blok da okunur", () => {
    // Cura'nın Elegoo eklentisi bloğu \r ile yazıyor; \r?\n bekleyen okuyucu bu dosyalarda
    // görsel bulamıyordu (ölçüldü: 354 dosyanın 4'ü).
    const png = pngOlcuyle(32, 32);
    const b64 = png.toString("base64");
    const blok = `; thumbnail begin 32 32 ${png.length}\r; ${b64}\r; thumbnail end\r`;
    const r = gcodeOnizlemesi(blok);
    expect(r).not.toBeNull();
    expect(r!.genislik).toBe(32);
  });

  it("ölçü ayracı boşluk da olabilir (32 32)", () => {
    const png = pngOlcuyle(64, 64);
    const b64 = png.toString("base64");
    const r = gcodeOnizlemesi(`; thumbnail begin 64 64 ${png.length}\n; ${b64}\n; thumbnail end\n`);
    expect(r!.genislik).toBe(64);
  });
});

// ───────────────────────── 3MF (zip) ─────────────────────────

/** Çok girdili gerçek bir zip kur (saklanmış ya da deflate). */
function zipCoklu(girdiler: { ad: string; icerik: Buffer }[], deflate: boolean): Buffer {
  const yontem = deflate ? 8 : 0;
  const yereller: Buffer[] = [];
  const merkezler: Buffer[] = [];
  let ofset = 0;

  for (const g of girdiler) {
    const adB = Buffer.from(g.ad, "utf8");
    const veri = deflate ? zlib.deflateRawSync(g.icerik) : g.icerik;

    const yerel = Buffer.alloc(30);
    yerel.writeUInt32LE(0x04034b50, 0);
    yerel.writeUInt16LE(yontem, 8);
    yerel.writeUInt32LE(veri.length, 18);
    yerel.writeUInt32LE(g.icerik.length, 22);
    yerel.writeUInt16LE(adB.length, 26);
    yerel.writeUInt16LE(0, 28);
    const yerelTam = Buffer.concat([yerel, adB, veri]);
    yereller.push(yerelTam);

    const merkez = Buffer.alloc(46);
    merkez.writeUInt32LE(0x02014b50, 0);
    merkez.writeUInt16LE(yontem, 10);
    merkez.writeUInt32LE(veri.length, 20);
    merkez.writeUInt32LE(g.icerik.length, 24);
    merkez.writeUInt16LE(adB.length, 28);
    merkez.writeUInt32LE(ofset, 42);
    merkezler.push(Buffer.concat([merkez, adB]));

    ofset += yerelTam.length;
  }

  const yerelBlok = Buffer.concat(yereller);
  const merkezBlok = Buffer.concat(merkezler);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0);
  eocd.writeUInt16LE(girdiler.length, 8);
  eocd.writeUInt16LE(girdiler.length, 10);
  eocd.writeUInt32LE(merkezBlok.length, 12);
  eocd.writeUInt32LE(yerelBlok.length, 16);

  return Buffer.concat([yerelBlok, merkezBlok, eocd]);
}

/** Tek girdili kısayol. */
function zipKur(ad: string, icerik: Buffer, deflate: boolean): Buffer {
  return zipCoklu([{ ad, icerik }], deflate);
}

function okuyucu(buf: Buffer): AralikOkuyucu {
  return async (a, b) => buf.subarray(a, b + 1);
}

describe("3MF zip önizlemesi", () => {
  it("SAKLANMIŞ girdiden plaka görselini çıkarır", async () => {
    const png = pngOlcuyle(512, 512);
    const zip = zipKur("Metadata/plate_1.png", png, false);
    const r = await zip3mfOnizlemesi(okuyucu(zip), zip.length);
    expect(r).not.toBeNull();
    expect(r!.genislik).toBe(512);
    expect(r!.png.subarray(1, 4).toString()).toBe("PNG");
  });

  it("DEFLATE girdiyi açar", async () => {
    const png = pngOlcuyle(256, 256);
    const zip = zipKur("Metadata/plate_1.png", png, true);
    const r = await zip3mfOnizlemesi(okuyucu(zip), zip.length);
    expect(r!.genislik).toBe(256);
  });

  it("GCODE HANGİ PLAKADANSA O plakanın görseli seçilir", async () => {
    /**
     * Gerçek dosyalarda 157 baskının 21'i plate_1 DEĞİL. Körü körüne plate_1 seçmek
     * kartta bambaşka bir parçayı gösteriyordu ("Delorean Arka Tampon" plate_5 basarken
     * plate_1 görünüyordu). Basılacak plakayı gcode belirler.
     */
    const yanlis = pngOlcuyle(111, 111); // plate_1 — bu GÖSTERİLMEMELİ
    const dogru = pngOlcuyle(512, 512); // plate_5 — gcode bundan
    const zip = zipCoklu(
      [
        { ad: "Metadata/plate_1.png", icerik: yanlis },
        { ad: "Metadata/plate_5.png", icerik: dogru },
        { ad: "Metadata/plate_5.gcode", icerik: Buffer.from("G1 X0\n") },
      ],
      false
    );
    const r = await zip3mfOnizlemesi(okuyucu(zip), zip.length);
    expect(r).not.toBeNull();
    expect(r!.genislik).toBe(512);
  });

  it("gcode plakası okunamazsa eski davranışa (plate_1) döner", async () => {
    const zip = zipCoklu(
      [
        { ad: "Metadata/plate_1.png", icerik: pngOlcuyle(300, 300) },
        { ad: "Metadata/plate_2.png", icerik: pngOlcuyle(400, 400) },
      ],
      false
    );
    const r = await zip3mfOnizlemesi(okuyucu(zip), zip.length);
    expect(r!.genislik).toBe(300);
  });

  it("plaka görseli yoksa null", async () => {
    const zip = zipKur("3D/3dmodel.model", Buffer.from("<model/>"), true);
    expect(await zip3mfOnizlemesi(okuyucu(zip), zip.length)).toBeNull();
  });

  it("bozuk zip patlatmaz, null döner", async () => {
    const cop = Buffer.alloc(500, 7);
    expect(await zip3mfOnizlemesi(okuyucu(cop), cop.length)).toBeNull();
  });

  it("boş dosyada null", async () => {
    expect(await zip3mfOnizlemesi(okuyucu(Buffer.alloc(0)), 0)).toBeNull();
  });

  it("DOSYANIN TAMAMI okunmaz — yalnız kuyruk, dizin ve girdi", async () => {
    /**
     * 65 MB'lık bir 3MF'i tamamen indirmek kartı dakikalarca bekletirdi. Bu test okuyucuya
     * gelen toplam bayt miktarını sayar; dosya boyutunun küçük bir kesri olmalı.
     */
    const png = pngOlcuyle(512, 512);
    const zip = zipKur("Metadata/plate_1.png", png, false);
    // Dosyayı yapay olarak büyüt: başa dolgu koyup ofsetleri kaydırmak yerine, okunan
    // bayt sayısını gerçek zip üzerinden ölçmek yeterli.
    let okunan = 0;
    const sayan: AralikOkuyucu = async (a, b) => {
      okunan += b - a + 1;
      return zip.subarray(a, b + 1);
    };
    const r = await zip3mfOnizlemesi(sayan, zip.length);
    expect(r).not.toBeNull();
    // Kuyruk okuması dosyanın tamamını kapsayabilir (test zip'i küçük); önemli olan
    // girdi başına TEK okuma yapılması — toplam, dosyanın birkaç katını AŞMAMALI.
    expect(okunan).toBeLessThan(zip.length * 3);
  });
});
