/**
 * EKSİK EXCLUDE_OBJECT KOMUTLARINI EKLEME (yükleme öncesi dönüşüm).
 *
 * ÖLÇÜLDÜ (25 Ağu 2026, kullanıcının U1'inde o an basılan gerçek dosya):
 *   gcode_label_objects = 1   → `; printing object …` yorumları VAR
 *   exclude_object      = 0   → EXCLUDE_OBJECT komutu SIFIR
 * Klipper yorumları okumaz, komutları ister. Panelde parça iptalinin hiç açılamamasının
 * sebebi buydu — yazıcı desteklemediği için değil, dosyada bilgi olmadığı için.
 *
 * Buradaki testlerin ortak sözleşmesi: **yalnız EKLEME yapılır.** Dosyanın kalanına
 * dokunulursa baskı bozulur ve bunu ancak yazıcının başında fark ederiz.
 *
 * (Klipper'ın parametre kaçışlaması ve nesne listesi ayıklaması `exclude-object.test.ts`
 * dosyasında; o kurallar buradaki üretimde de aynen kullanılıyor.)
 */
import { describe, expect, it } from "vitest";
import { excludeObjectEkle, excludeObjectKomutuVar } from "./exclude-object";

/** Gerçek dosyadaki biçimin aynısı (U1'den okundu). */
const A = "pistone (1) (1) id:8589938692 copy 0";
const B = "pistone (1) (1) id:1179653 copy 0";

function ornek(): Buffer {
  return Buffer.from(
    [
      "; generated by Snapmaker Orca 2.3.5",
      "G28",
      `; printing object ${A}`,
      "G1 X10.5 Y20.5 E0.1",
      "G1 X30.5 Y40.5 E0.2",
      `; stop printing object ${A}`,
      "G1 X0 Y0",
      `; printing object ${B}`,
      "G1 X110 Y120 E0.1",
      "G1 X130 Y140 E0.2",
      `; stop printing object ${B}`,
      "M84",
      "",
    ].join("\n"),
    "latin1",
  );
}

describe("dokunulmaması gereken dosyalar", () => {
  it("EXCLUDE_OBJECT zaten varsa null döner", () => {
    const buf = Buffer.from("EXCLUDE_OBJECT_DEFINE NAME=x\n; printing object x\nG1 X1 Y1\n", "latin1");
    expect(excludeObjectKomutuVar(buf)).toBe(true);
    expect(excludeObjectEkle(buf)).toBeNull();
  });

  it("hiç etiket yoksa null döner", () => {
    expect(excludeObjectEkle(Buffer.from("G28\nG1 X1 Y1\nM84\n", "latin1"))).toBeNull();
  });

  it("ölçüsü çıkarılamayan parça varsa dönüşüm YAPILMAZ", () => {
    // Yarım bilgiyle çizilen bir seçici, kullanıcıyı YANLIŞ parçayı iptal etmeye götürebilir.
    const buf = Buffer.from(`; printing object ${A}\n; stop printing object ${A}\nM84\n`, "latin1");
    expect(excludeObjectEkle(buf)).toBeNull();
  });
});

describe("dönüşüm", () => {
  it("her parça için DEFINE üretir — merkez ve çokgenle", () => {
    const r = excludeObjectEkle(ornek())!;
    expect(r.parcalar.map((p) => p.ad)).toEqual([A, B]);
    const metin = r.cikti.toString("latin1");
    expect(metin).toContain("EXCLUDE_OBJECT_DEFINE");
    expect(metin).toContain("CENTER=");
    expect(metin).toContain("POLYGON=");
  });

  it("sınır kutusu gerçek hareketlerden çıkarılıyor", () => {
    const r = excludeObjectEkle(ornek())!;
    expect([r.parcalar[0].minX, r.parcalar[0].maxX, r.parcalar[0].minY, r.parcalar[0].maxY])
      .toEqual([10.5, 30.5, 20.5, 40.5]);
    expect([r.parcalar[1].minX, r.parcalar[1].maxX, r.parcalar[1].minY, r.parcalar[1].maxY])
      .toEqual([110, 130, 120, 140]);
  });

  it("START hareketlerden ÖNCE, END sonra giriyor", () => {
    const metin = excludeObjectEkle(ornek())!.cikti.toString("latin1");
    const s = metin.indexOf("EXCLUDE_OBJECT_START");
    const hareket = metin.indexOf("G1 X10.5 Y20.5");
    const e = metin.indexOf("EXCLUDE_OBJECT_END");
    expect(s).toBeGreaterThan(0);
    expect(s).toBeLessThan(hareket);
    expect(e).toBeGreaterThan(hareket);
  });

  it("YALNIZ EKLEME: özgün satırların hepsi çıktıda aynen duruyor", () => {
    // Bu dosyanın en önemli testi. Bir bayt bile değişirse baskı bozulur.
    const girdi = ornek().toString("latin1");
    const cikti = excludeObjectEkle(ornek())!.cikti.toString("latin1");
    for (const satir of girdi.split("\n")) {
      if (!satir.trim()) continue;
      expect(cikti, `özgün satır kayboldu: ${satir}`).toContain(satir);
    }
    expect(cikti.length).toBeGreaterThan(girdi.length);
  });

  it("yorumlar korunuyor (OctoPrint uyumu + insan okunurluğu)", () => {
    const cikti = excludeObjectEkle(ornek())!.cikti.toString("latin1");
    expect(cikti).toContain(`; printing object ${A}`);
    expect(cikti).toContain(`; stop printing object ${A}`);
  });

  it("aynı parça birden çok blokta geçse de TEK tanım üretilir", () => {
    const buf = Buffer.from(
      [
        `; printing object ${A}`, "G1 X10 Y10", `; stop printing object ${A}`,
        `; printing object ${A}`, "G1 X50 Y60", `; stop printing object ${A}`, "",
      ].join("\n"),
      "latin1",
    );
    const r = excludeObjectEkle(buf)!;
    expect(r.parcalar.length).toBe(1);
    // Kutu İKİ bloğu birden kapsamalı — yoksa seçicide parça yarım çizilir.
    expect([r.parcalar[0].minX, r.parcalar[0].maxX]).toEqual([10, 50]);
    expect(r.cikti.toString("latin1").split("EXCLUDE_OBJECT_DEFINE").length - 1).toBe(1);
  });

  it("tehlikeli karakterli ad KAÇIŞLANIYOR — sessizce kırpılmasın", () => {
    /**
     * Klipper shlex kullanıyor ve '#' yorum başlatıyor: tırnaksız `NAME=part#1` sessizce
     * "part"a kırpılır → YANLIŞ parça iptal edilir, hata da çıkmaz.
     */
    const buf = Buffer.from(
      "; printing object part#1 copy 0\nG1 X5 Y5\n; stop printing object part#1 copy 0\n",
      "latin1",
    );
    const metin = excludeObjectEkle(buf)!.cikti.toString("latin1");
    expect(metin).toContain('NAME="part#1 copy 0"');
  });

  it("TÜRKÇE ad bayt bayt korunuyor — Moonraker'ın göreceğiyle aynı olmalı", () => {
    /**
     * Ad okuma/yazma bilerek `latin1` ile yapılıyor: o kodlama bayt-geçirgendir, yani
     * dosyadaki UTF-8 baytları bozulmadan geri yazılır. Bu şart, çünkü Klipper'a
     * gönderdiğimiz NAME ile Moonraker'ın sonradan bildireceği ad AYNI olmalı; bir bayt
     * kayarsa iptal komutu sessizce hiçbir şeyi eşleştirmez.
     *
     * (Dizge olarak karşılaştırmak yanıltıcı olur — burada önemli olan BAYTLAR.)
     */
    const ad = "Çiçeği_ID_2";
    const adBayt = Buffer.from(ad, "utf8");
    const buf = Buffer.concat([
      Buffer.from("; printing object ", "latin1"), adBayt,
      Buffer.from("\nG1 X5 Y5\n; stop printing object ", "latin1"), adBayt,
      Buffer.from("\n", "latin1"),
    ]);
    const cikti = excludeObjectEkle(buf)!.cikti;
    // Üretilen DEFINE satırındaki ad, özgün baytların aynısı olmalı.
    expect(cikti.includes(Buffer.concat([Buffer.from("NAME=", "latin1"), adBayt]))).toBe(true);
    // Ve dosyadaki özgün yorum da bozulmamış olmalı.
    expect(cikti.includes(adBayt)).toBe(true);
  });
});
