/**
 * Gcode başlığı ayrıştırıcıları — Elegoo Neptune'lerde SÜRE, KÜÇÜK RESİM ve RENGİN hiç
 * okunmaması gerilemesinin koruması.
 *
 * Canlı tanı (12 Ağu): `/server/files/metadata` Neptune 4 Pro/Plus'ta yalnız
 * `size, modified, print_start_time, job_id, filename` döndürüyor. Dilimleyici bunların hepsini
 * dosyaya yazmış: başta 320×320 ve 800×800 küçük resim blokları, sonda süre/renk/katman satırları.
 * Aşağıdaki örnekler bu dosyalardan BİREBİR alındı.
 */
import { describe, expect, it } from "vitest";
import {
  parseGcodeThumbnails, pickLargestThumbnail, thumbnailDataUrl,
  parseGcodeEstimatedTimeSec, parseGcodeFilamentColours, parseGcodeFilamentTypes,
  parseGcodeFilamentGrams,
} from "./gcode-header";

const HEAD = [
  "; HEADER_BLOCK_START",
  "; generated by OrcaSlicer 2.3.2 on 2026-06-03 at 13:44:52",
  "; total layer number: 371",
  "; HEADER_BLOCK_END",
  "; THUMBNAIL_BLOCK_START",
  ";",
  "; thumbnail begin 320x320 31312",
  "; QUlPTA==",
  "; QUlPTQ==",
  "; thumbnail end",
  "; THUMBNAIL_BLOCK_END",
  ";gimage:0`000200000P0000?<?M1FH0001S0@0",
  "; thumbnail begin 800x800 131940",
  "; Qk9PTQ==",
  "; thumbnail end",
  "; THUMBNAIL_BLOCK_END",
  "G1 X10 Y10",
].join("\n");

const TAIL = [
  "; filament used [mm] = 10229.32",
  "; filament used [g] = 30.51",
  "; total filament used [g] = 30.51",
  "; total layers count = 371",
  "; estimated printing time (normal mode) = 2h 0m 50s",
  "; estimated first layer printing time (normal mode) = 21s",
  "; filament_colour = #FFFFFF",
  "; filament_type = PLA",
  "; layer_height = 0.2",
].join("\n");

describe("gömülü küçük resim", () => {
  it("EN BÜYÜK çözünürlüklü bloğu seçer", () => {
    const list = parseGcodeThumbnails(HEAD);
    expect(list.map((t) => `${t.width}x${t.height}`)).toEqual(["320x320", "800x800"]);
    expect(pickLargestThumbnail(list)).toMatchObject({ width: 800, height: 800 });
  });

  it("blok satırlarını birleştirip data URL üretir", () => {
    const t = pickLargestThumbnail(parseGcodeThumbnails(HEAD))!;
    expect(thumbnailDataUrl(t)).toBe("data:image/png;base64,Qk9PTQ==");
  });

  it("kapanmamış blok ATILIR — yarım base64 kırık görsel demek", () => {
    // 256 KB'lık Range isteği bloğun ortasında bitmiş olabilir.
    const kesik = "; thumbnail begin 800x800 131940\n; Qk9PTQ==\n; QUlP";
    expect(parseGcodeThumbnails(kesik)).toEqual([]);
  });

  it("Elegoo'nun kendi `;gimage:` önizlemesini küçük resim SANMAZ", () => {
    // ⚠️ Eski hâli yalnız HEAD'e bakıyordu; oradaki `;gimage:` satırı zaten hiçbir açık bloğun
    // İÇİNDE değil, yani ayrıştırıcı bozulsa da test geçiyordu. Asıl risk, `;gimage:` satırının
    // açık bir bloğun ortasına düşmesi: base64'e karışırsa görsel kırılır.
    const karisik = [
      "; thumbnail begin 320x320 8",
      "; Qk9P",
      ";gimage:AAECAwQFBgcICQoLDA0ODw==",
      "; TQ==",
      "; thumbnail end",
    ].join("\n");
    const list = parseGcodeThumbnails(karisik);
    expect(list).toHaveLength(1);
    expect(list[0].base64).toBe("Qk9PTQ==");
    expect(thumbnailDataUrl(list[0])).toBe("data:image/png;base64,Qk9PTQ==");
  });
});

describe("dilimleyici süre tahmini", () => {
  it("Orca biçimini saniyeye çevirir", () => {
    expect(parseGcodeEstimatedTimeSec(TAIL)).toBe(2 * 3600 + 50);
  });

  it("gün içeren tahmini de okur", () => {
    expect(parseGcodeEstimatedTimeSec("; estimated printing time (normal mode) = 1d 2h 3m 4s"))
      .toBe(86400 + 2 * 3600 + 3 * 60 + 4);
  });

  it("Cura biçimini okur", () => {
    expect(parseGcodeEstimatedTimeSec(";TIME:7250")).toBe(7250);
  });

  it("bilinmiyorsa null döner (sıfır DEĞİL)", () => {
    expect(parseGcodeEstimatedTimeSec("; hiçbir şey")).toBeNull();
  });
});

describe("filament bilgisi", () => {
  it("rengi büyük harf hex olarak döndürür", () => {
    expect(parseGcodeFilamentColours(TAIL)).toEqual(["#FFFFFF"]);
  });

  it("çok filamentli dosyada renkleri sırayla döndürür", () => {
    expect(parseGcodeFilamentColours("; filament_colour = #000000;#FFFFFF;#F4EE2A"))
      .toEqual(["#000000", "#FFFFFF", "#F4EE2A"]);
  });

  it("tipleri tekilleştirir", () => {
    expect(parseGcodeFilamentTypes("; filament_type = PLA;PLA;PETG")).toEqual(["PLA", "PETG"]);
  });

  it("gramajı okur (yalnız gösterim amaçlı)", () => {
    expect(parseGcodeFilamentGrams(TAIL)).toBe(30.51);
  });
});
