/**
 * Gcode tarayıcı testleri.
 *
 * NEDEN VARLAR: eski ayrıştırıcıda `MAX_SEG = 900_000` sabit bir tavandı ve ana döngünün koşulu
 * `segCount < MAX_SEG` idi. Tavan dolunca tarama dosyanın ORTASINDA duruyordu — hiçbir hata
 * verilmeden. Yazıcının bastığı 178 MB'lık gerçek dosyada bu, 1333 katmanın yalnız 172'sinin
 * (yüksekliğin %12,8'i) çizilmesi demekti: kartta görünen leke figürün kaidesiydi.
 * Buradaki testler "bütçe dolsa bile modelin TAMAMI paketlenir" kuralını kilitler.
 *
 * Ayrıca araç (T0/T1) izleme, katman→bayt indeksi ve özellik sınıflandırması sınanır: bunlar
 * sırasıyla gerçek filament renklerini, canlı katman göstergesini ve "gövde baskın" kart
 * görselini besleyen alanlardır.
 */
import { describe, expect, it } from "vitest";
import {
  GcodeScanner, scanGcodeText, parseGcode,
  FEATURE_OUTER, FEATURE_INNER, FEATURE_INFILL, FEATURE_SOLID, FEATURE_SUPPORT, FEATURE_SKIRT,
  featureCode, isBodyFeature, layerAtBytePosition, encodeVizPack, decodeVizPack, expandPack,
} from "./parse-gcode";

/** Katman başına dörtgen bir çerçeve basan sentetik Orca-stili gcode üretir. */
function makeGcode(layers: number, pointsPerLayer: number, opts?: { tools?: boolean }): string {
  const out: string[] = ["; generated by test", "M83"];
  for (let l = 0; l < layers; l++) {
    const z = +(0.2 * (l + 1)).toFixed(3);
    out.push(";LAYER_CHANGE", `;Z:${z}`);
    if (opts?.tools) out.push(l % 2 === 0 ? "T0" : "T1");
    out.push(";TYPE:Outer wall");
    out.push(`G1 X10 Y10 Z${z} F9000`);
    for (let i = 0; i < pointsPerLayer; i++) {
      // Dairesel yol — düz olmadığı için sadeleştirme hepsini yutamaz.
      const a = (i / pointsPerLayer) * Math.PI * 2;
      const x = (50 + 30 * Math.cos(a)).toFixed(3);
      const y = (50 + 30 * Math.sin(a)).toFixed(3);
      out.push(`G1 X${x} Y${y} E0.05`);
    }
  }
  return out.join("\n") + "\n";
}

describe("gcode tarayıcı — sessiz kesme yok", () => {
  it("bütçe dolsa bile SON katman pakete girer (eski 900k tavanı modeli ortadan kesiyordu)", () => {
    const layers = 200;
    const text = makeGcode(layers, 40);
    // Tam çözünürlükte kaç nokta çıktığını ölç, sonra bütçeyi onun çok altına indir.
    const full = scanGcodeText(text);
    const tight = scanGcodeText(text, { maxPoints: Math.floor(full.points.length / 2 / 6) });

    expect(tight.thinLevel).toBeGreaterThan(0); // gerçekten seyreltmeye zorlandık
    expect(tight.layerZ.length).toBe(layers);   // katman sayısı KORUNDU
    expect(tight.layerZ[layers - 1]).toBeCloseTo(0.2 * layers, 3); // en üst katman duruyor
    expect(tight.bounds.maxZ).toBeCloseTo(full.bounds.maxZ, 3);
    // Üst yarıda hâlâ çizim var — seyreltme her yere eşit dağılır, tepe kaybolmaz.
    const half = Math.floor(layers / 2);
    const topPaths = tight.layerPathEnd[layers - 1] - tight.layerPathStart[half];
    expect(topPaths).toBeGreaterThan(0);
  });

  it("her katmanda segment kalır (tepe katmanlar boşalmaz)", () => {
    const g = parseGcode(makeGcode(120, 30), { maxPoints: 4000 });
    const empty = g.layerRanges.filter((r) => r.end === r.start).length;
    expect(empty).toBe(0);
    expect(g.layerRanges.length).toBe(120);
  });

  it("taranan segment sayısı paketlenenden büyük olabilir ama kayıp RAPORLANIR", () => {
    const p = scanGcodeText(makeGcode(60, 40), { maxPoints: 600 });
    expect(p.thinLevel).toBeGreaterThan(0);
    expect(p.scannedSegments).toBeGreaterThan(p.segmentCount);
    expect(p.segmentCount).toBeGreaterThan(0);
  });
});

describe("gcode tarayıcı — akış sınırları", () => {
  it("parçalara bölünmüş besleme tek seferlik beslemeyle AYNI sonucu verir", () => {
    const text = makeGcode(40, 25);
    const bytes = new TextEncoder().encode(text);
    const once = scanGcodeText(text);

    const sc = new GcodeScanner({ fileSize: bytes.length });
    // Kasten satır sınırlarına denk gelmeyen tuhaf parça boyu.
    for (let i = 0; i < bytes.length; i += 37) sc.push(bytes.subarray(i, Math.min(bytes.length, i + 37)));
    const streamed = sc.finish();

    expect(streamed.layerZ.length).toBe(once.layerZ.length);
    expect(streamed.segmentCount).toBe(once.segmentCount);
    expect(Array.from(streamed.layerByteOffset)).toEqual(Array.from(once.layerByteOffset));
  });
});

describe("katman ↔ dosya bayt konumu", () => {
  it("katman bayt konumları artan sıradadır ve gidiş-dönüş kayıpsızdır", () => {
    const p = scanGcodeText(makeGcode(50, 12));
    for (let i = 1; i < p.layerByteOffset.length; i++) {
      expect(p.layerByteOffset[i]).toBeGreaterThan(p.layerByteOffset[i - 1]);
    }
    for (let i = 0; i < p.layerByteOffset.length; i++) {
      expect(layerAtBytePosition(p.layerByteOffset, p.layerByteOffset[i] + 5)).toBe(i);
    }
  });

  it("dosya başı 0. katmana, dosya sonu son katmana düşer", () => {
    const p = scanGcodeText(makeGcode(20, 8));
    expect(layerAtBytePosition(p.layerByteOffset, 0)).toBe(0);
    expect(layerAtBytePosition(p.layerByteOffset, 1e12)).toBe(p.layerByteOffset.length - 1);
    expect(layerAtBytePosition(new Float64Array(0), 100)).toBe(-1);
  });

  it("ilk katman başlangıç gcode'unu içerir → katman sayısı dilimleyicininkiyle eşleşir", () => {
    // Purge çizgisi ilk ;LAYER_CHANGE'ten ÖNCE gelir; ayrı bir katman AÇMAMALI.
    const text = [
      "M83", ";TYPE:Custom", "G1 X5 Y5 Z0.2 F9000", "G1 X200 Y5 E12",
      ";LAYER_CHANGE", ";Z:0.2", ";TYPE:Outer wall", "G1 X10 Y10 E0.1", "G1 X20 Y10 E0.1",
      ";LAYER_CHANGE", ";Z:0.4", ";TYPE:Outer wall", "G1 X10 Y10 E0.1", "G1 X20 Y12 E0.1",
    ].join("\n");
    const p = scanGcodeText(text);
    expect(p.layerZ.length).toBe(2);
    expect(p.layerByteOffset[0]).toBe(0);
  });
});

describe("araç (kafa) izleme — gerçek filament renkleri", () => {
  it("T0/T1 komutları segmentlere araç indeksi olarak yazılır", () => {
    const g = parseGcode(makeGcode(6, 10, { tools: true }));
    expect(g.toolCount).toBe(2);
    const inLayer = (i: number) => g.tools[g.layerRanges[i].start];
    expect(inLayer(0)).toBe(0);
    expect(inLayer(1)).toBe(1);
    expect(inLayer(2)).toBe(0);
  });

  it("T-1 / T255 gibi 'araç yok' işaretleri aktif aracı bozmaz", () => {
    const text = [
      "M83", ";LAYER_CHANGE", ";Z:0.2", "T1", ";TYPE:Outer wall",
      "G1 X10 Y10 E0.1", "G1 X20 Y10 E0.1", "T255", "G1 X30 Y10 E0.1",
    ].join("\n");
    const g = parseGcode(text);
    expect(g.toolCount).toBe(2);
    for (let i = 0; i < g.totalSegments; i++) expect(g.tools[i]).toBe(1);
  });

  it("dilimleyicinin bildirdiği filament renkleri pakete taşınır", () => {
    const text = [
      "; filament_colour = #000000;#FFFFFF;#F4EE2A", "M83",
      ";LAYER_CHANGE", ";Z:0.2", ";TYPE:Outer wall", "G1 X10 Y10 E0.1", "G1 X20 Y10 E0.1",
    ].join("\n");
    const p = scanGcodeText(text);
    expect(p.filamentColors).toEqual(["#000000", "#FFFFFF", "#F4EE2A"]);
  });
});

describe("özellik sınıflandırması — gövde ile dolgu ayrımı", () => {
  it("'Internal solid infill' KATI gövdedir, seyrek dolgu değil", () => {
    // Eski kod 'infill' geçtiği için bunu seyrek dolgu sayıyor, modelin etini geri plana atıyordu.
    expect(featureCode("Internal solid infill")).toBe(FEATURE_SOLID);
    expect(featureCode("Gap infill")).toBe(FEATURE_SOLID);
    expect(featureCode("Top surface")).toBe(FEATURE_SOLID);
    expect(featureCode("Bridge")).toBe(FEATURE_SOLID);
    expect(isBodyFeature(FEATURE_SOLID)).toBe(true);
  });

  it("gövde olmayanlar doğru ayrılır", () => {
    expect(featureCode("Sparse infill")).toBe(FEATURE_INFILL);
    expect(featureCode("Support interface")).toBe(FEATURE_SUPPORT);
    expect(featureCode("Prime tower")).toBe(FEATURE_SKIRT);
    expect(featureCode("Skirt")).toBe(FEATURE_SKIRT);
    expect(isBodyFeature(FEATURE_INFILL)).toBe(false);
    expect(isBodyFeature(FEATURE_SUPPORT)).toBe(false);
    expect(isBodyFeature(FEATURE_SKIRT)).toBe(false);
  });

  it("duvar tipleri doğru ayrılır", () => {
    expect(featureCode("Outer wall")).toBe(FEATURE_OUTER);
    expect(featureCode("Overhang wall")).toBe(FEATURE_OUTER);
    expect(featureCode("Inner wall")).toBe(FEATURE_INNER);
  });

  it("segmentler dosyadaki ;TYPE etiketine göre işaretlenir", () => {
    const text = [
      "M83", ";LAYER_CHANGE", ";Z:0.2",
      ";TYPE:Outer wall", "G1 X10 Y10 E0.1", "G1 X30 Y10 E0.1",
      ";TYPE:Sparse infill", "G1 X10 Y20 E0.1", "G1 X30 Y20 E0.1",
      ";TYPE:Internal solid infill", "G1 X10 Y30 E0.1", "G1 X30 Y30 E0.1",
    ].join("\n");
    const g = parseGcode(text);
    const seen = new Set(Array.from(g.features));
    expect(seen.has(FEATURE_OUTER)).toBe(true);
    expect(seen.has(FEATURE_INFILL)).toBe(true);
    expect(seen.has(FEATURE_SOLID)).toBe(true);
  });
});

describe("katman işareti OLMAYAN dosyalar (Z yedeği)", () => {
  /**
   * Yedek yolun kendini kapatması: `newLayer()` ilk iş olarak `sawLayerMarker = true` yapıyordu,
   * oysa yedeğin koşulu `!sawLayerMarker`. Yedek ömrü boyunca YALNIZ BİR KEZ çalışıyor, dosyanın
   * tamamı tek katmana yığılıyordu (katman kaydırıcısı tek kademe, canlı dolum ilerlemiyor).
   */
  function noMarkerGcode(layers: number): string {
    const out: string[] = ["; dilimleyici katman yorumu yazmıyor", "M83"];
    for (let l = 0; l < layers; l++) {
      const z = +(0.2 * (l + 1)).toFixed(3);
      out.push(`G1 X10 Y10 Z${z} F9000`);
      out.push(`G1 X40 Y10 Z${z} E0.1`);
      out.push(`G1 X40 Y40 Z${z} E0.1`);
      out.push(`G1 X10 Y40 Z${z} E0.1`);
    }
    return out.join("\n") + "\n";
  }

  it("Z her arttığında yeni katman açılır (yedek bir kez çalışıp susmaz)", () => {
    const p = scanGcodeText(noMarkerGcode(10));
    expect(p.layerZ.length).toBe(10);
    expect(p.layerZ[0]).toBeCloseTo(0.2, 3);
    expect(p.layerZ[9]).toBeCloseTo(2.0, 3);
  });

  it("katman bayt konumları hâlâ artan sıradadır (canlı katman göstergesi çalışır)", () => {
    const p = scanGcodeText(noMarkerGcode(6));
    for (let i = 2; i < p.layerByteOffset.length; i++) {
      expect(p.layerByteOffset[i]).toBeGreaterThan(p.layerByteOffset[i - 1]);
    }
    expect(layerAtBytePosition(p.layerByteOffset, p.layerByteOffset[4] + 3)).toBe(4);
  });

  it("AÇIK katman işareti varken Z yedeği devreye GİRMEZ (çift katman yok)", () => {
    // Vazo modunda Z her hareket artar; işaret varsa katman sayısı işaretten gelmeli.
    const text = [
      "M83",
      ";LAYER_CHANGE", ";Z:0.2", ";TYPE:Outer wall",
      "G1 X10 Y10 Z0.21 E0.1", "G1 X20 Y10 Z0.22 E0.1", "G1 X30 Y10 Z0.23 E0.1",
      ";LAYER_CHANGE", ";Z:0.4", ";TYPE:Outer wall",
      "G1 X10 Y20 Z0.41 E0.1", "G1 X20 Y20 Z0.42 E0.1",
    ].join("\n");
    expect(scanGcodeText(text).layerZ.length).toBe(2);
  });
});

describe("paket ikili biçimi", () => {
  /**
   * ⚠️ TEK ŞEKİL YETMEZ. Bölümler 4 bayta hizalanıyordu ama son bölüm (`layerByteOffset`) bir
   * Float64Array ve `new Float64Array(buffer, offset, n)` offset'in 8'in KATI olmasını şart
   * koşar. Offset başlık uzunluğuna ve nokta/yol/katman sayılarına bağlı olduğu için paketlerin
   * yaklaşık YARISI `RangeError` ile çözülemiyordu — kodlama hatasızdı, hata yalnız OKUMADA
   * çıkıyordu. Eski test tek bir şanslı şekil (15×20) denediği için yeşil kalıyordu.
   */
  const SHAPES: [layers: number, points: number][] = [
    [1, 2], [1, 3], [2, 2], [3, 3], [3, 5], [3, 7], [3, 8], [3, 9],
    [4, 9], [5, 4], [7, 11], [9, 6], [12, 13], [15, 20], [23, 7], [40, 12],
  ];

  for (const [layers, points] of SHAPES) {
    for (const tools of [false, true]) {
      it(`${layers} katman × ${points} nokta${tools ? " (2 araç)" : ""} → çözülebilir ve kayıpsız`, () => {
        const p = scanGcodeText(makeGcode(layers, points, { tools }));
        const round = decodeVizPack(encodeVizPack(p));
        expect(round.layerZ.length).toBe(p.layerZ.length);
        expect(round.segmentCount).toBe(p.segmentCount);
        expect(Array.from(round.points)).toEqual(Array.from(p.points));
        expect(Array.from(round.layerByteOffset)).toEqual(Array.from(p.layerByteOffset));
      });
    }
  }

  it("başlık uzunluğu değişse de (filament renkleri) paket çözülür", () => {
    // Başlık JSON'u bölüm başlangıçlarını kaydırır; hizalama hatası tam da burada patlıyordu.
    for (let n = 0; n <= 6; n++) {
      const colors = Array.from({ length: n }, (_, i) => `#${i}${i}${i}${i}${i}${i}`).join(";");
      const head = n ? `; filament_colour = ${colors}` : "; renk yok";
      const p = scanGcodeText(`${head}\n${makeGcode(3, 5)}`);
      const round = decodeVizPack(encodeVizPack(p));
      expect(Array.from(round.layerByteOffset)).toEqual(Array.from(p.layerByteOffset));
    }
  });

  it("kodla-çöz gidiş dönüşü geometriyi korur", () => {
    const p = scanGcodeText(makeGcode(15, 20, { tools: true }));
    const round = decodeVizPack(encodeVizPack(p));

    expect(round.segmentCount).toBe(p.segmentCount);
    expect(round.layerZ.length).toBe(p.layerZ.length);
    expect(round.toolCount).toBe(p.toolCount);
    expect(Array.from(round.points)).toEqual(Array.from(p.points));
    expect(Array.from(round.layerByteOffset)).toEqual(Array.from(p.layerByteOffset));

    // Kuantizasyon kaybı ekstrüzyon genişliğinin çok altında kalmalı.
    const a = expandPack(p), b = expandPack(round);
    let maxErr = 0;
    for (let i = 0; i < a.positions.length; i++) maxErr = Math.max(maxErr, Math.abs(a.positions[i] - b.positions[i]));
    expect(maxErr).toBeLessThan(0.01);
  });

  it("kuantizasyon gerçek koordinatlara 0,01 mm'den yakın kalır", () => {
    const text = [
      "M83", ";LAYER_CHANGE", ";Z:0.2", ";TYPE:Outer wall",
      "G1 X10.123 Y20.987 F9000", // seyahat: kalem buraya taşınır, çizim yok
      "G1 X155.777 Y99.001 E0.1",
    ].join("\n");
    const g = parseGcode(text);
    expect(g.totalSegments).toBe(1);
    expect(g.positions[0]).toBeCloseTo(10.123, 2);
    expect(g.positions[1]).toBeCloseTo(20.987, 2);
    expect(g.positions[3]).toBeCloseTo(155.777, 2);
    expect(g.positions[4]).toBeCloseTo(99.001, 2);
  });

  it("boş/çizimsiz dosya sessizce boş paket verir (çökmeden)", () => {
    const p = scanGcodeText("; sadece yorum\nM104 S200\n");
    expect(p.segmentCount).toBe(0);
    expect(expandPack(p).totalSegments).toBe(0);
  });
});
